Add the persistent data section
OpenLiberty/guide-liberty-deep-dive-gradle pull request #20
Opened 2023-06-15 16:39 UTC by shin19991207

2023-06-15 21:50 UTC, gkwan-ibm requested changes
**Additional prerequisites**
- [ ] "Before you begin, Podman needs to be installed." -> "Before you begin, Podman needs to be installed before you start the **Persisting Data** module."

Update the following scripts for gradlew or podman:
- [ ] scripts/finishPersistingData.sh
- [ ] scripts/finishPersistingData.bat
- [ ] scripts/startPostgres.sh
- [ ] scripts/startPostgres.bat
- [ ] scripts/stopPostgres.sh
- [ ] scripts/stopPostgres.bat

Test:
- [ ] update the testApp.sh to test the Persisting Data module

2023-06-27 09:07 UTC, jakub-pomykala submitted a review, later dismissed

2023-08-30 21:52 UTC, gkwan-ibm commented
This PR is blocked by https://github.com/OpenLiberty/ci.gradle/issues/842

2023-09-06 19:40 UTC, gkwan-ibm approved these changes

2023-09-06 20:17 UTC, merged